### ISSUE TITLE
git clone fails?

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/publication-figures#2]
```
git clone git@github.com:vanvalenlab/publication-figures.git

Cloning into 'publication-figures'...
remote: Enumerating objects: 317, done.
remote: Counting objects: 100% (317/317), done.
remote: Compressing objects: 100% (211/211), done.
remote: Total 317 (delta 140), reused 268 (delta 98), pack-reused 0
Receiving objects: 100% (317/317), 104.14 KiB | 820.00 KiB/s, done.
Resolving deltas: 100% (140/140), done.

warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

**Comment by willgraf** [comment]
When executing the command I do hit an error:

```
git clone git@github.com/vanvalenlab/publication-figures.git
Cloning into 'publication-figures'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

However, cloning using the GitHub repository URL works as expected:

```
git clone https://github.com/vanvalenlab/publication-figures.git
```

**Comment by dylanbannon** [comment]
Just to confirm, you were in a folder where the repo didn't already exist when you executed `git clone https://github.com/vanvalenlab/publication-figures.git`? Can you show me your output, because even that's failing for me?

**Comment by dylanbannon** [comment]
Oh, I'm sorry! It does work! It's just going extremely slowly. This must be a huge repo.

**Comment by willgraf** [comment]
I think there's a lot of data saved in the `new_data/` folder.

Since the clone command is working for you, Is this issue resolved?

**Comment by dylanbannon** [comment]
I bet you're right about the data. Maybe a good use case for something like git-lfs in the future.

It is resolved, though.
