### ISSUE TITLE
Cellpose & StarDist models trainned on TissueNet

### ISSUE THREAD

**Issue by LPUoO** [vanvalenlab/publication-figures#9]
Hello @ngreenwald, 

Are the Cellpose & StarDist models trainned on TissueNet (Figure 2 B, [doi:10.1038/s41587-021-01094-0](https://www.nature.com/articles/s41587-021-01094-0), also [here](https://twitter.com/NoahGreenwald/status/1461370582335844355/photo/1)) available for download?

Thank you

**Comment by ngreenwald** [comment]
They're not currently, but we can definitely upload them. Just need to track down the files
